### ISSUE TITLE
Is MKL crucial, or is it optional?

### ISSUE THREAD

**Issue by PetrKryslUCSD** [msmerlak/IterativePerturbationTheory.jl#1]
I would like to try out this package, but I do not have MKL installed.
Is this fatal?

**Comment by msmerlak** [comment]
No, should work equally well OpenBLAS: simply remove the calls to MKL packages

**Comment by PetrKryslUCSD** [comment]
Having to remove references to MKL from the package source is not convenient for users.
It might be better to have it optional.

**Comment by msmerlak** [comment]
Ok, I'll comment out these lines.
