### ISSUE TITLE
Are there some examples (tests)?

### ISSUE THREAD

**Issue by PetrKryslUCSD** [msmerlak/IterativePerturbationTheory.jl#3]
What about those from your paper?

**Comment by msmerlak** [comment]
Thanks for the tip. This is my first real open source project; I'm still learning good practices and usage. I'll try to figure out how tests work in Julia and where to put them in the repo

**Comment by PetrKryslUCSD** [comment]
Adding tests is easy: 
1. Add a directory `test` at the same level as `src`.
2. Add a file `runtests.jl` in this directory. Possible contents:
```
using Test
@time @testset "Utilities" begin
    include("test_utilities.jl")
end
```
In this case, there is a file `test_utilities.jl` with the actual tests. For instance
```
module mutil001

using Test
using LinearAlgebra
using FinEtools

function _test()
   SM = AssemblyModule
   a = SM.SysmatAssemblerSparseCSRSymm(0.0)                    
   ...                                      
   A1 = makematrix!(a) 
   @test norm(A - A1) / norm(A1) < 1.0e-9
   return true
end

_test()

end # module
```
3. Test the package as `using Pkg; Pkg.test();`.

**Comment by msmerlak** [comment]
@PetrKryslUCSD I've added tests, looks good to you?
